-- =========================================
-- RLS FOR public.config (Ticket 101 follow-up)
-- =========================================
-- Server-side guard for the config table, replacing the client-only
-- `isAdmin` check that used to live in src/stores/config.js.
-- Safe to re-run: table creation is guarded by IF NOT EXISTS, policies
-- are dropped and recreated.

-- Table is created only if it does not already exist in Supabase.
CREATE TABLE IF NOT EXISTS public.config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT,
    sort_order INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
    );

COMMENT ON TABLE public.config IS 'Anwendungskonfiguration (key/value)';

ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;

-- SELECT is public: /info is an unauthenticated page and reads
-- config.public_phone_number without a session.
DROP POLICY IF EXISTS "Allow public read config" ON public.config;
CREATE POLICY "Allow public read config"
  ON public.config FOR SELECT
  TO public
  USING (true);

-- Only active admins may write config values. This is now the only
-- enforcement point for updateConfig() — the client-side check was
-- removed as UX-only in ConfigView.vue.
DROP POLICY IF EXISTS "Allow admins to manage config" ON public.config;
CREATE POLICY "Allow admins to manage config"
  ON public.config FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.user_id = auth.uid()
      AND users.role = 'admin'
      AND users.active = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.user_id = auth.uid()
      AND users.role = 'admin'
      AND users.active = true
    )
  );

-- =========================================
-- End of migration
-- =========================================
