npx supabase secrets set SUPABASE_URL="https://prlivcmqjqjypclkcovl.supabase.co"

npx supabase secrets set SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybGl2Y21xanFqeXBjbGtjb3ZsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDE0NzAxMiwiZXhwIjoyMDY5NzIzMDEyfQ.b3xnNfoIOc288HuuxNQzDXivNfiEDgFxq8XIylwYeQk"
pause
