-- =========================================
-- CHECKPOINTS (Ticket 131)
-- =========================================
-- Real implementation of the "Контрольная точка / Checkpoint" entity
-- designed in tickets/130/decision.md and tickets/130/IMPLEMENTATION_PLAN.md,
-- and UX-validated as a UI-only mock in ticket 130_2 (4 rounds of user
-- feedback, src/composables/useCheckpointsMock.js). This script adds:
--   1. checkpoints (new table) - one row per Bus/Group/Lazy roll-call round.
--   2. scan_packets.checkpoint_id - links each received packet to the round
--      it belongs to (doc/db/scan_packets.sql did not have this column yet).
--   3. RLS: SELECT only for authenticated; no INSERT/UPDATE/DELETE policy -
--      writes only via SECURITY DEFINER functions, see
--      doc/db/checkpoints_functions.sql and
--      doc/db/checkpoints_scan_packets_extension.sql.
--
-- Deliberate deviation from tickets/130/IMPLEMENTATION_PLAN.md's original
-- schema: no CANCELLED status (3), no cancelled_at/cancelled_by columns.
-- The 130_2 prototype replaced "Cancel" with two clearer actions after real
-- user feedback (Round 1) - reopenCheckpoint() (undo a Finish) and
-- removeCheckpoint() (fully delete an erroneously-created checkpoint). The
-- real remove_checkpoint() (see checkpoints_functions.sql) hard-deletes the
-- checkpoint and cascades to its scan_packets/scans procedurally - by
-- explicit user instruction, accepting the data-loss risk as low (packets
-- can be resent from the counselor's device). See
-- tickets/131/IMPLEMENTATION_PLAN.md for the full rationale.
--
-- Apply manually via the Supabase SQL editor (this repo has no migrations
-- folder, see doc/db/scan_packets.sql for the same convention). Safe to
-- re-run: CREATE TABLE IF NOT EXISTS, columns added IF NOT EXISTS, policies
-- dropped and recreated.
--
-- Ordering: apply this file BEFORE doc/db/checkpoints_functions.sql and
-- doc/db/checkpoints_scan_packets_extension.sql (both reference
-- public.checkpoints / scan_packets.checkpoint_id).

-- =========================================
-- 1) New table: checkpoints
-- =========================================
CREATE TABLE IF NOT EXISTS public.checkpoints (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type smallint NOT NULL,             -- 1=BUS, 2=GROUP, 3=LAZY - same codes as scan_packets.type
  day character varying NOT NULL,     -- same format as scans.date/scan_packets.date
  status smallint NOT NULL DEFAULT 1, -- 1=OPEN, 2=FINISHED (no CANCELLED, see header)
  created_by bigint NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NULL,
  finished_by bigint NULL REFERENCES public.users(id),
  baseline_children_count integer NULL, -- set by finish_checkpoint() only for the first FINISHED checkpoint of the day (any type)
  CONSTRAINT checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT checkpoints_type_check CHECK (type IN (1, 2, 3)),
  CONSTRAINT checkpoints_status_check CHECK (status IN (1, 2))
);

-- Not more than one OPEN checkpoint per type per day - types are independent
-- and may run in parallel (tickets/130/decision.md, п.3-4): a Bus checkpoint
-- and a Group checkpoint may both be open at once, that's normal; conflict
-- is only possible between two checkpoints of the SAME type.
CREATE UNIQUE INDEX IF NOT EXISTS idx_checkpoints_one_open_per_type_per_day
  ON public.checkpoints(day, type) WHERE status = 1;

CREATE INDEX IF NOT EXISTS idx_checkpoints_day ON public.checkpoints(day);

-- =========================================
-- 2) scan_packets.checkpoint_id
-- =========================================
ALTER TABLE public.scan_packets
  ADD COLUMN IF NOT EXISTS checkpoint_id bigint NULL REFERENCES public.checkpoints(id);
-- Plain FK, no ON DELETE action override - remove_checkpoint() deletes
-- dependent scan_packets/scans rows explicitly (checkpoints_functions.sql),
-- so no CASCADE is needed on this FK.

CREATE INDEX IF NOT EXISTS idx_scan_packets_checkpoint_id
  ON public.scan_packets(checkpoint_id) WHERE checkpoint_id IS NOT NULL;

-- =========================================
-- 3) RLS for checkpoints
-- =========================================
ALTER TABLE public.checkpoints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "checkpoints_select_authenticated" ON public.checkpoints;
CREATE POLICY "checkpoints_select_authenticated"
  ON public.checkpoints FOR SELECT
  TO authenticated
  USING (true);

-- No INSERT/UPDATE/DELETE policy for authenticated is created on purpose:
-- writes happen only through create_checkpoint()/finish_checkpoint()/
-- remove_checkpoint() (doc/db/checkpoints_functions.sql, admin path) and
-- submit_scan_packet() (doc/db/checkpoints_scan_packets_extension.sql,
-- auto-create path) - both SECURITY DEFINER / service_role, bypassing RLS
-- by design. Do NOT add a permissive "just in case" write policy here - see
-- vault/03-База-данных/RLS-политики.md, "Неотозванные широкие
-- legacy-политики", for why that exact pattern has already made narrower
-- policies meaningless elsewhere in this project (children_today/
-- groups_today/reset_events/children/days).

-- =========================================
-- End of migration
-- =========================================
