-- =========================================
-- CHECKPOINTS (Ticket 132)
-- =========================================
-- Server side of the "Checkpoint" (Kontrollpunkt) hybrid model, see
-- tickets/130/decision.md ("Принятое решение") and
-- tickets/131/MIGRATION_PLAN.md for the overall sequencing (132-139). Adds:
--   1. checkpoints (new entity - a roll-call control point, one per
--      type/day while OPEN, see the partial unique index below)
--   2. scan_packets.checkpoint_id (links existing packets to the point they
--      were counted into)
--   3. RLS: SELECT only for authenticated, no INSERT/UPDATE/DELETE policy -
--      writes only through the SECURITY DEFINER functions below (see note
--      near the policy block and vault/03-База-данных/RLS-политики.md,
--      "Неотозванные широкие legacy-политики" - this table is designed to
--      not repeat that mistake from day one).
--   4. Four admin RPC functions: create_checkpoint/finish_checkpoint/
--      reopen_checkpoint/remove_checkpoint - explicit administrator actions,
--      error shapes mirror src/composables/useCheckpointsMock.js 1:1
--      (tickets/133 depends on this contract, see "Error contract" below).
--   5. submit_scan_packet() extension (CREATE OR REPLACE, same function
--      tickets/120/122 already call via the submit-scan-packet Edge
--      Function) - auto-creates/finds the open checkpoint of a packet's
--      type/day. A packet is never rejected for lacking a checkpoint - this
--      is the central property of the hybrid model (decision.md, "1.
--      Перекличка создается автоматически").
--
-- Error contract for the four RPC functions: RAISE EXCEPTION '<CODE>' (no
-- interpolation) for the plain-code errors (NOT_OPEN, NOT_FINISHED,
-- NOT_FOUND). For ALREADY_OPEN, which also carries an existingId
-- (useCheckpointsMock.js: {error:'ALREADY_OPEN', existingId}), the id is
-- passed via the Postgres DETAIL field (RAISE ... USING DETAIL = id::text) -
-- supabase-js surfaces this as error.details on the RPC call's error object,
-- so the composable layer (ticket 133) can do
-- `if (error.message === 'ALREADY_OPEN') return { error: 'ALREADY_OPEN', existingId: Number(error.details) }`
-- without a second round-trip.
--
-- Apply manually via the Supabase SQL editor (this repo has no migrations
-- folder, see doc/db/scan_packets.sql for the same convention). Safe to
-- re-run: CREATE TABLE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS, CREATE INDEX
-- IF NOT EXISTS, CREATE OR REPLACE FUNCTION throughout.

-- =========================================
-- 1) New table: checkpoints
-- =========================================
CREATE TABLE IF NOT EXISTS public.checkpoints (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type smallint NOT NULL,                -- 1=BUS, 2=GROUP, 3=LAZY
  day character varying NOT NULL,        -- same format as scans.date/scan_packets.date
  status smallint NOT NULL DEFAULT 1,    -- 1=OPEN, 2=FINISHED (no CANCELLED - see reopen/remove below)
  created_by bigint NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NULL,
  finished_by bigint NULL REFERENCES public.users(id),
  baseline_children_count smallint NULL,
  CONSTRAINT checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT checkpoints_type_check CHECK (type IN (1, 2, 3)),
  CONSTRAINT checkpoints_status_check CHECK (status IN (1, 2))
);

-- Central mechanism of the hybrid model (decision.md, "4. Одновременно
-- может существовать только одна открытая перекличка каждого типа"): at
-- most one OPEN checkpoint per (day, type). Both create_checkpoint() and the
-- submit_scan_packet() auto-create path rely on this index - the former
-- rejects the conflict explicitly, the latter uses it as an ON CONFLICT
-- target to resolve races between two Betreuer submitting the first packet
-- of the day simultaneously (see the comment on submit_scan_packet() below).
CREATE UNIQUE INDEX IF NOT EXISTS checkpoints_open_type_per_day
  ON public.checkpoints (day, type) WHERE status = 1;

CREATE INDEX IF NOT EXISTS idx_checkpoints_day ON public.checkpoints (day);

-- =========================================
-- 2) Link scan_packets to the checkpoint they were counted into
-- =========================================
ALTER TABLE public.scan_packets
  ADD COLUMN IF NOT EXISTS checkpoint_id bigint NULL REFERENCES public.checkpoints(id);

CREATE INDEX IF NOT EXISTS idx_scan_packets_checkpoint_id ON public.scan_packets(checkpoint_id) WHERE checkpoint_id IS NOT NULL;

-- =========================================
-- 3) RPC: create_checkpoint
-- =========================================
-- Explicit administrator creation (decision.md, "2. Перекличка завершается
-- только главным администратором" - the counterpart action for opening one
-- ahead of time, e.g. before the morning BUS count starts). Unlike the
-- auto-create path in submit_scan_packet(), this one is NOT silent about a
-- conflict - it rejects, mirroring useCheckpointsMock.js createCheckpoint().
CREATE OR REPLACE FUNCTION public.create_checkpoint(p_type smallint, p_day character varying)
RETURNS public.checkpoints AS $$
DECLARE
  v_admin_id bigint;
  v_existing_id bigint;
  v_row public.checkpoints;
BEGIN
  SELECT id INTO v_admin_id FROM public.users
  WHERE user_id = auth.uid() AND role = 'admin' AND active = true;

  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'NOT_ADMIN';
  END IF;

  SELECT id INTO v_existing_id FROM public.checkpoints
  WHERE day = p_day AND type = p_type AND status = 1;

  IF v_existing_id IS NOT NULL THEN
    RAISE EXCEPTION 'ALREADY_OPEN' USING DETAIL = v_existing_id::text;
  END IF;

  INSERT INTO public.checkpoints (type, day, status, created_by)
  VALUES (p_type, p_day, 1, v_admin_id)
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================
-- 4) RPC: finish_checkpoint
-- =========================================
-- Only explicit way to close a checkpoint (decision.md, "2." - no
-- auto-finish, not even for LAZY). Two separately commented steps, not one
-- opaque transaction (tickets/131/131.txt, "Ограничения"):
--   step 1 - close the checkpoint itself;
--   step 2 - if this is the first FINISHED checkpoint of the day (any
--            type), freeze baseline_children_count. Computed from
--            scans/scan_packets directly (not children_today/groups_today -
--            those are not date-scoped yet, see ticket 138), scoped to only
--            this checkpoint's own packets - matches
--            useCheckpointsMock.js computePresentCount()/finishCheckpoint().
CREATE OR REPLACE FUNCTION public.finish_checkpoint(p_id bigint)
RETURNS public.checkpoints AS $$
DECLARE
  v_admin_id bigint;
  v_row public.checkpoints;
  v_is_first_of_day boolean;
  v_baseline smallint;
BEGIN
  SELECT id INTO v_admin_id FROM public.users
  WHERE user_id = auth.uid() AND role = 'admin' AND active = true;

  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'NOT_ADMIN';
  END IF;

  -- Step 1: close the checkpoint.
  UPDATE public.checkpoints
  SET status = 2, finished_at = now(), finished_by = v_admin_id
  WHERE id = p_id AND status = 1
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'NOT_OPEN';
  END IF;

  -- Step 2: baseline, only for the first FINISHED checkpoint of the day
  -- (independent of type - decision.md, "Roster" section: presentRoster is
  -- fixed by the first roll-call of the day, whichever type it is).
  SELECT NOT EXISTS (
    SELECT 1 FROM public.checkpoints
    WHERE day = v_row.day AND baseline_children_count IS NOT NULL
  ) INTO v_is_first_of_day;

  IF v_is_first_of_day THEN
    SELECT COUNT(DISTINCT s.child_id) INTO v_baseline
    FROM public.scans s
    JOIN public.scan_packets sp ON sp.id = s.packet_id
    WHERE sp.checkpoint_id = p_id;

    UPDATE public.checkpoints
    SET baseline_children_count = v_baseline
    WHERE id = p_id
    RETURNING * INTO v_row;
  END IF;

  RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================
-- 5) RPC: reopen_checkpoint
-- =========================================
-- Undo for an accidental Finish (UX feedback round 1, tickets/130_2) -
-- replaces the earlier CANCELLED-status idea entirely, see
-- tickets/130/decision.md history and useCheckpointsMock.js reopenCheckpoint().
-- Only valid for status=2; rejects with the same ALREADY_OPEN shape as
-- create_checkpoint() if another checkpoint of the same type/day was opened
-- in the meantime (the partial unique index would reject the UPDATE anyway -
-- this check produces the structured error instead of a raw constraint
-- violation).
CREATE OR REPLACE FUNCTION public.reopen_checkpoint(p_id bigint)
RETURNS public.checkpoints AS $$
DECLARE
  v_admin_id bigint;
  v_cp public.checkpoints;
  v_existing_id bigint;
  v_row public.checkpoints;
BEGIN
  SELECT id INTO v_admin_id FROM public.users
  WHERE user_id = auth.uid() AND role = 'admin' AND active = true;

  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'NOT_ADMIN';
  END IF;

  SELECT * INTO v_cp FROM public.checkpoints WHERE id = p_id AND status = 2;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'NOT_FINISHED';
  END IF;

  SELECT id INTO v_existing_id FROM public.checkpoints
  WHERE day = v_cp.day AND type = v_cp.type AND status = 1;

  IF v_existing_id IS NOT NULL THEN
    RAISE EXCEPTION 'ALREADY_OPEN' USING DETAIL = v_existing_id::text;
  END IF;

  UPDATE public.checkpoints
  SET status = 1, finished_at = NULL, finished_by = NULL
  WHERE id = p_id
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================
-- 6) RPC: remove_checkpoint
-- =========================================
-- Removes an erroneously created checkpoint entirely (replaces the earlier
-- CANCELLED-status idea, see useCheckpointsMock.js removeCheckpoint() and
-- tickets/130_2 UX feedback round 1). Cascades via three explicit DELETEs,
-- NOT via ON DELETE CASCADE on scans.packet_id (that would change the
-- behaviour of any future scan_packets deletion, not just this button).
--
-- Explicit consequence, not hidden: after this call, the client_packet_id
-- values of the deleted packets become free again, so a Betreuer's offline
-- retry of the same packet is no longer deduplicated by
-- submit_scan_packet()'s ON CONFLICT (client_packet_id) DO NOTHING - it will
-- be accepted as a new packet (and may auto-create a new checkpoint). This
-- is the accepted risk from tickets/131/MIGRATION_PLAN_REVIEW_RESPONSE.md.
CREATE OR REPLACE FUNCTION public.remove_checkpoint(p_id bigint)
RETURNS public.checkpoints AS $$
DECLARE
  v_admin_id bigint;
  v_row public.checkpoints;
BEGIN
  SELECT id INTO v_admin_id FROM public.users
  WHERE user_id = auth.uid() AND role = 'admin' AND active = true;

  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'NOT_ADMIN';
  END IF;

  SELECT * INTO v_row FROM public.checkpoints WHERE id = p_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'NOT_FOUND';
  END IF;

  DELETE FROM public.scans
  WHERE packet_id IN (SELECT id FROM public.scan_packets WHERE checkpoint_id = p_id);

  DELETE FROM public.scan_packets WHERE checkpoint_id = p_id;

  DELETE FROM public.checkpoints WHERE id = p_id;

  RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================
-- 7) submit_scan_packet() extension - auto-create/find checkpoint
-- =========================================
-- CREATE OR REPLACE of the existing function (doc/db/scan_packets.sql,
-- tickets/120/122) - full body preserved, only the checkpoint
-- auto-create/find step and passing checkpoint_id through to scan_packets
-- are new. The children[] guard, client_packet_id idempotency and the scans
-- insert are unchanged.
--
-- Race safety: two Betreuer submitting the first packet of the day for the
-- same type simultaneously both attempt the INSERT below. The partial
-- unique index checkpoints_open_type_per_day makes the second INSERT hit
-- ON CONFLICT ... DO NOTHING instead of erroring, and the subsequent SELECT
-- (ORDER BY id DESC LIMIT 1) reads whichever row actually committed -
-- both callers converge on the same checkpoint_id, no packet is ever
-- rejected for this reason (decision.md, "1. Перекличка создается
-- автоматически").
CREATE OR REPLACE FUNCTION submit_scan_packet(payload jsonb)
RETURNS TABLE(packet_id bigint, created boolean) AS $$
DECLARE
  v_packet_id bigint;
  v_client_packet_id uuid := (payload->>'client_packet_id')::uuid;
  v_checkpoint_id bigint;
BEGIN
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(COALESCE(payload->'children', '[]'::jsonb)) AS c
    WHERE NULLIF(c->>'child_id', '') IS NULL
  ) THEN
    RAISE EXCEPTION 'Packet children[] contains an entry without child_id - payload malformed';
  END IF;

  -- Auto-create/find the open checkpoint of this packet's type/day (see
  -- race-safety note above). No RAISE EXCEPTION here on purpose - a packet
  -- is never rejected for lacking a checkpoint, that is the central
  -- difference from the classic manual-open model (decision.md).
  INSERT INTO checkpoints (type, day, status, created_by)
  VALUES ((payload->>'type_code')::smallint, payload->>'date', 1, (payload->>'author_id')::bigint)
  ON CONFLICT (day, type) WHERE status = 1 DO NOTHING;

  SELECT id INTO v_checkpoint_id FROM checkpoints
  WHERE day = payload->>'date' AND type = (payload->>'type_code')::smallint AND status = 1
  ORDER BY id DESC LIMIT 1;

  INSERT INTO scan_packets (
    client_packet_id, type, author_id, bus_id, group_id,
    date, started_at, finished_at, children_count, checkpoint_id
  )
  VALUES (
    v_client_packet_id,
    (payload->>'type_code')::smallint,
    (payload->>'author_id')::bigint,
    NULLIF(payload->>'bus_id', '')::smallint,
    NULLIF(payload->>'group_id', '')::smallint,
    payload->>'date',
    NULLIF(payload->>'started_at', '')::timestamptz,
    (payload->>'finished_at')::timestamptz,
    jsonb_array_length(COALESCE(payload->'children', '[]'::jsonb)),
    v_checkpoint_id
  )
  ON CONFLICT (client_packet_id) DO NOTHING
  RETURNING id INTO v_packet_id;

  IF v_packet_id IS NULL THEN
    -- Already exists: either a retry after a lost response, or a race between
    -- two simultaneous retries (either way - do not create again).
    SELECT id INTO v_packet_id FROM scan_packets WHERE client_packet_id = v_client_packet_id;
    RETURN QUERY SELECT v_packet_id, false;
    RETURN;
  END IF;

  INSERT INTO scans (date, user_id, child_id, bus_id, type, packet_id, method, created_at)
  SELECT
    payload->>'date',
    (payload->>'author_id')::bigint,
    (c->>'child_id')::bigint,
    NULLIF(payload->>'bus_id', '')::smallint,
    1,
    v_packet_id,
    CASE WHEN c->>'method' = 'MANUAL' THEN 2 ELSE 1 END,
    COALESCE(NULLIF(c->>'timestamp', '')::timestamptz, now())
  FROM jsonb_array_elements(COALESCE(payload->'children', '[]'::jsonb)) AS c;

  RETURN QUERY SELECT v_packet_id, true;
END;
$$ LANGUAGE plpgsql;

-- =========================================
-- 8) RLS for checkpoints
-- =========================================
ALTER TABLE public.checkpoints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "checkpoints_select_authenticated" ON public.checkpoints;
CREATE POLICY "checkpoints_select_authenticated"
  ON public.checkpoints FOR SELECT
  TO authenticated
  USING (true);

-- No INSERT/UPDATE/DELETE policy for authenticated is created on purpose:
-- writes happen only through create_checkpoint()/finish_checkpoint()/
-- reopen_checkpoint()/remove_checkpoint() (SECURITY DEFINER, explicit
-- role='admin' AND active=true check) and through submit_scan_packet()
-- (called only by the submit-scan-packet Edge Function via the
-- service_role client, which RLS does not apply to). Do NOT add a
-- permissive "just in case" write policy here - see
-- vault/03-База-данных/RLS-политики.md, "Неотозванные широкие
-- legacy-политики", for why that exact pattern has already made a narrower
-- policy meaningless elsewhere in this project (children_today/
-- groups_today/reset_events/children/days) - checkpoints is designed to not
-- repeat it from day one.

-- =========================================
-- End of migration
-- =========================================
