-- =========================================
-- SCAN PACKETS (Ticket 122)
-- =========================================
-- Server-side counterpart to Ticket 120: the client (src/composables/useScanPacket.js)
-- now sends one batch PresencePacket per "Senden" instead of one scans row per
-- child. This script adds:
--   1. scan_packets (new packet-header entity, idempotency anchor)
--   2. scans.packet_id / scans.method (compatible extension)
--   3. on_scan_insert / on_children_today_change reworked from FOR EACH ROW to
--      FOR EACH STATEMENT (transition tables), so a batch INSERT of N children
--      triggers one recalculation cycle instead of N (tickets/121, tickets/122).
--   4. submit_scan_packet(payload jsonb) - atomic idempotent packet intake,
--      called only from the submit-scan-packet Edge Function via the
--      service_role client (never directly by authenticated users).
--   5. RLS: SELECT only for authenticated on scan_packets; no INSERT/UPDATE/
--      DELETE policy is added for authenticated - see note near the policy
--      block below and vault/03-База-данных/RLS-политики.md ("Неотозванные
--      широкие legacy-политики").
-- Apply manually via the Supabase SQL editor (this repo has no migrations
-- folder, see doc/db_triggers.sql / doc/db/headcount_presence_morning.sql for
-- the same convention). Safe to re-run: CREATE TABLE IF NOT EXISTS, functions
-- and triggers are replaced/recreated, columns are added IF NOT EXISTS.

-- =========================================
-- 1) New table: scan_packets (packet header)
-- =========================================
CREATE TABLE IF NOT EXISTS public.scan_packets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_packet_id uuid NOT NULL,
  type smallint NOT NULL,               -- 1=BUS, 2=GROUP, 3=CHECKIN
  author_id bigint NOT NULL REFERENCES public.users(id),
  bus_id smallint NULL,
  group_id smallint NULL,
  date character varying NOT NULL,       -- same format as scans.date
  started_at timestamptz NULL,
  finished_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  children_count smallint NOT NULL DEFAULT 0,
  cancelled_at timestamptz NULL,         -- reserved for future cancel feature (121, §10), unused in 122
  CONSTRAINT scan_packets_pkey PRIMARY KEY (id),
  CONSTRAINT scan_packets_client_packet_id_key UNIQUE (client_packet_id),
  CONSTRAINT scan_packets_type_check CHECK (type IN (1, 2, 3)),
  CONSTRAINT scan_packets_bus_group_check CHECK (
    (type = 1 AND bus_id IS NOT NULL AND group_id IS NULL) OR
    (type = 2 AND group_id IS NOT NULL AND bus_id IS NULL) OR
    (type = 3 AND bus_id IS NULL AND group_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_scan_packets_bus_date ON public.scan_packets(bus_id, date) WHERE bus_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_scan_packets_group_date ON public.scan_packets(group_id, date) WHERE group_id IS NOT NULL;

-- =========================================
-- 2) Compatible extension of scans
-- =========================================
ALTER TABLE public.scans
  ADD COLUMN IF NOT EXISTS packet_id bigint NULL REFERENCES public.scan_packets(id),
  ADD COLUMN IF NOT EXISTS method smallint NOT NULL DEFAULT 1; -- 1=SCAN, 2=MANUAL

CREATE INDEX IF NOT EXISTS idx_scans_packet_id ON public.scans(packet_id) WHERE packet_id IS NOT NULL;

-- =========================================
-- 3) Batch trigger rework
-- =========================================
-- Problem: a single N-row INSERT into scans used to fire the row-level
-- trigger N times (see doc/db_triggers.sql). Fix: PostgreSQL transition
-- tables (REFERENCING NEW TABLE AS new_table, available since PG10) - the
-- statement-level trigger fires once per statement regardless of row count,
-- and also once for the existing single-row insert paths
-- (ChildDetailView.vue -> useScan.createScan(), tickets/120/122.txt), so no
-- branching by source is needed.

CREATE OR REPLACE FUNCTION on_scan_insert_batch()
RETURNS TRIGGER AS $$
BEGIN
  -- DISTINCT ON guards against two rows for the same child_id within one
  -- statement (client dedupes within a round via isDuplicate(), but the
  -- server must not rely on that - INSERT ... ON CONFLICT fails outright if
  -- the statement itself contains two conflicting rows for the same key).
  INSERT INTO children_today (
    user_id, child_id, group_id,
    presence_today, presence_now, bus_today, bus_now, presence_morning
  )
  SELECT DISTINCT ON (s.child_id)
    s.user_id, s.child_id, c.group_id,
    1, 1, s.bus_id, s.bus_id,
    CASE WHEN s.bus_id IS NOT NULL THEN 1 ELSE 0 END
  FROM new_table s
  JOIN children c ON c.id = s.child_id
  ORDER BY s.child_id, s.created_at DESC
  ON CONFLICT (child_id) DO UPDATE
    SET presence_now = 1,
        bus_now = EXCLUDED.bus_now,
        user_id = EXCLUDED.user_id;
    -- presence_morning intentionally not in the SET list, same invariant as
    -- the row-level version (ticket 106, doc/db/headcount_presence_morning.sql)
  RETURN NULL; -- statement-level trigger, NEW/OLD are not available
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_on_scan_insert ON scans;
CREATE TRIGGER trg_on_scan_insert
  AFTER INSERT ON scans
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT
  EXECUTE FUNCTION on_scan_insert_batch();

CREATE OR REPLACE FUNCTION on_children_today_change_batch()
RETURNS TRIGGER AS $$
BEGIN
  -- Full COUNT(*) FILTER per affected group (not an increment) - same
  -- race-safety property as the row-level version, just scoped to "every
  -- distinct group touched by this statement" instead of "one call per row".
  INSERT INTO groups_today (user_id, group_id, children_today, children_now)
  SELECT
    MAX(ct.user_id),
    ct.group_id,
    COUNT(*) FILTER (WHERE ct.presence_today = 1),
    COUNT(*) FILTER (WHERE ct.presence_now = 1)
  FROM children_today ct
  WHERE ct.group_id IN (
    SELECT DISTINCT group_id FROM new_table WHERE group_id IS NOT NULL
  )
  GROUP BY ct.group_id
  ON CONFLICT (group_id) DO UPDATE
    SET children_today = EXCLUDED.children_today,
        children_now = EXCLUDED.children_now,
        user_id = EXCLUDED.user_id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_on_children_today_change ON children_today;
CREATE TRIGGER trg_on_children_today_change
  AFTER INSERT OR UPDATE ON children_today
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT
  EXECUTE FUNCTION on_children_today_change_batch();

-- Not reworked, untouched by this script (unrelated to batch scan insertion):
-- on_reset_event_insert, on_children_today_delete, recalculate_groups_today().

-- =========================================
-- 4) Packet intake function
-- =========================================
-- One INSERT for the header + one INSERT for all child rows, inside one
-- function = one implicit transaction: any failure rolls back both (atomicity,
-- tickets/121 §8). author_id/type_code in payload are set by the Edge
-- Function, not taken from the client request body as-is - this function
-- does not authenticate the caller itself, that already happened at the Edge
-- Function level, which calls this function via the service_role client.
CREATE OR REPLACE FUNCTION submit_scan_packet(payload jsonb)
RETURNS TABLE(packet_id bigint, created boolean) AS $$
DECLARE
  v_packet_id bigint;
  v_client_packet_id uuid := (payload->>'client_packet_id')::uuid;
BEGIN
  INSERT INTO scan_packets (
    client_packet_id, type, author_id, bus_id, group_id,
    date, started_at, finished_at, children_count
  )
  VALUES (
    v_client_packet_id,
    (payload->>'type_code')::smallint,
    (payload->>'author_id')::bigint,
    NULLIF(payload->>'bus_id', '')::smallint,
    NULLIF(payload->>'group_id', '')::smallint,
    payload->>'date',
    NULLIF(payload->>'started_at', '')::timestamptz,
    (payload->>'finished_at')::timestamptz,
    jsonb_array_length(COALESCE(payload->'children', '[]'::jsonb))
  )
  ON CONFLICT (client_packet_id) DO NOTHING
  RETURNING id INTO v_packet_id;

  IF v_packet_id IS NULL THEN
    -- Already exists: either a retry after a lost response, or a race between
    -- two simultaneous retries (either way - do not create again).
    SELECT id INTO v_packet_id FROM scan_packets WHERE client_packet_id = v_client_packet_id;
    RETURN QUERY SELECT v_packet_id, false;
    RETURN;
  END IF;

  INSERT INTO scans (date, user_id, child_id, bus_id, type, packet_id, method, created_at)
  SELECT
    payload->>'date',
    (payload->>'author_id')::bigint,
    (c->>'child_id')::bigint,
    NULLIF(payload->>'bus_id', '')::smallint,
    1,
    v_packet_id,
    CASE WHEN c->>'method' = 'MANUAL' THEN 2 ELSE 1 END,
    COALESCE(NULLIF(c->>'timestamp', '')::timestamptz, now())
  FROM jsonb_array_elements(COALESCE(payload->'children', '[]'::jsonb)) AS c;

  RETURN QUERY SELECT v_packet_id, true;
END;
$$ LANGUAGE plpgsql;

-- =========================================
-- 5) RLS for scan_packets
-- =========================================
ALTER TABLE public.scan_packets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "scan_packets_select_authenticated" ON public.scan_packets;
CREATE POLICY "scan_packets_select_authenticated"
  ON public.scan_packets FOR SELECT
  TO authenticated
  USING (true);

-- No INSERT/UPDATE/DELETE policy for authenticated is created on purpose:
-- writes happen only through submit_scan_packet(), called by the
-- submit-scan-packet Edge Function via the service_role client, which RLS
-- does not apply to. Do NOT add a permissive "just in case" write policy
-- here - see vault/03-База-данных/RLS-политики.md, "Неотозванные широкие
-- legacy-политики", for why that pattern has already made a narrower policy
-- meaningless elsewhere in this project (children_today/groups_today/
-- reset_events/children/days).

-- =========================================
-- End of migration
-- =========================================
