# /.github/workflows/deploy.yml
name: Deploy Vue/Vite app to GitHub Pages

on:
  push:
    branches:
      - main  # 🚀 Автодеплой при пуше в main
  workflow_dispatch:  # позволяет запустить вручную

permissions:
  contents: write  # нужно для пуша в gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ''  # Можно указать свой домен, если есть
